"""Add price breakdown to orders

Revision ID: d0311b1eafce
Revises: edf936f346cd
Create Date: 2026-05-13 17:27:38.458679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0311b1eafce'
down_revision: Union[str, Sequence[str], None] = 'edf936f346cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('subtotal', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('shipping_charges', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('tax', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tax')
    op.drop_column('orders', 'shipping_charges')
    op.drop_column('orders', 'subtotal')
    # ### end Alembic commands ###
